---
functional:
  - Пользователь должен иметь возможность регистрации на сайте, что бы оставить данные для обратной связи
  - Пользователь должен иметь возможность просматривать историю игр и их статистику в лк
  - Пользователь должен иметь возможность создать игру и настроить ее под себя
  - Пользователь должен иметь возможность иметь возможность играть, как с живыми участниками, так с ботами
  - Пользователь должен иметь возможность видеть остальных игроков, что в реальном времнеи находятся на сайте
  - Пользователь должен иметь возможность общаться с другими игроками в чате или лс
  - Пользователь должен иметь возможность вызвать другого игрока на совместную игру
  - Пользователь должен иметь возможность сам создавать новые задачи для игр
  - Пользователь должен иметь возможность просматривать запись игр, как своих, так и других игроков
  - Пользователь должен иметь возможность видеть таблицу лидеров с категориями - за неделю, за месяц, за всё время
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность выбора языка совоей страны, для всего сайта
